[project]
name = "blendrl-dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jax>=0.5.3",
    "nsfr",
    "nudge",
    "ocatari",
    "jaxatari"
]

[tool.uv.sources]
ocatari = { git = "https://github.com/k4ntz/OC_Atari" }
nsfr = {path = "./nsfr", editable = true}
nudge = {path = "./nudge", editable = true}
#jaxatari = {git = "https://github.com/k4ntz/JAXAtari"}
jaxatari = {path = "./JAXAtari", editable = true}
